/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.admin.alaiktomugi;

/**
 *
 * @author siadm
 */
public class kudeaketaPanela extends javax.swing.JFrame {

    /**
     * Creates new form kudeaketaPanela
     */
    public kudeaketaPanela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanela = new javax.swing.JPanel();
        HeaderTituloa = new javax.swing.JLabel();
        MenuPanela = new javax.swing.JPanel();
        GidariakKudeatuButton = new javax.swing.JButton();
        BidaiakIkusiButton = new javax.swing.JButton();
        ErabiltzaileakIkusiButton = new javax.swing.JButton();
        HistorialaButton = new javax.swing.JButton();
        PantallaNagusia = new javax.swing.JPanel();
        HistorikoajScrollPane = new javax.swing.JScrollPane();
        HistorikoaTable = new javax.swing.JTable();
        SakatutakoBotoiarenTituloa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderPanela.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        HeaderTituloa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HeaderTituloa.setText("KUDEAKETA SISTEMA");

        javax.swing.GroupLayout HeaderPanelaLayout = new javax.swing.GroupLayout(HeaderPanela);
        HeaderPanela.setLayout(HeaderPanelaLayout);
        HeaderPanelaLayout.setHorizontalGroup(
            HeaderPanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelaLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(HeaderTituloa)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        HeaderPanelaLayout.setVerticalGroup(
            HeaderPanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HeaderTituloa)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        MenuPanela.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        GidariakKudeatuButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GidariakKudeatuButton.setText("Gidariak Kudeatu");
        GidariakKudeatuButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        GidariakKudeatuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            }
        });
        GidariakKudeatuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GidariakKudeatuButtonActionPerformed(evt);
            }
        });

        BidaiakIkusiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BidaiakIkusiButton.setText("Bidaiak Ikusi");
        BidaiakIkusiButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BidaiakIkusiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BidaiakIkusiButtonActionPerformed(evt);
            }
        });

        ErabiltzaileakIkusiButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ErabiltzaileakIkusiButton.setText("Erabiltzaileak Ikusi");
        ErabiltzaileakIkusiButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ErabiltzaileakIkusiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErabiltzaileakIkusiButtonActionPerformed(evt);
            }
        });

        HistorialaButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HistorialaButton.setText("Historiala");
        HistorialaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        HistorialaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelaLayout = new javax.swing.GroupLayout(MenuPanela);
        MenuPanela.setLayout(MenuPanelaLayout);
        MenuPanelaLayout.setHorizontalGroup(
            MenuPanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GidariakKudeatuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BidaiakIkusiButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(ErabiltzaileakIkusiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(HistorialaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanelaLayout.setVerticalGroup(
            MenuPanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GidariakKudeatuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BidaiakIkusiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErabiltzaileakIkusiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HistorialaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PantallaNagusia.setBackground(new java.awt.Color(255, 255, 255));
        PantallaNagusia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        HistorikoaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },

            new String [] {
                "Amaiera data", "Amaiera ordua", "Jatorria", "Helmuga"
            }

        ));
        SakatutakoBotoiarenTituloa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SakatutakoBotoiarenTituloa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SakatutakoBotoiarenTituloa.setText("SAKATUTAKO BOTOIAREN TITULOA");
        SakatutakoBotoiarenTituloa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PantallaNagusiaLayout = new javax.swing.GroupLayout(PantallaNagusia);
        PantallaNagusia.setLayout(PantallaNagusiaLayout);
        PantallaNagusiaLayout.setHorizontalGroup(
            PantallaNagusiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HistorikoajScrollPane)
            .addComponent(SakatutakoBotoiarenTituloa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PantallaNagusiaLayout.setVerticalGroup(
            PantallaNagusiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaNagusiaLayout.createSequentialGroup()
                .addComponent(SakatutakoBotoiarenTituloa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistorikoajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HistorikoajScrollPane.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PantallaNagusia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuPanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PantallaNagusia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GidariakKudeatuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GidariakKudeatuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GidariakKudeatuButtonActionPerformed

    private void BidaiakIkusiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BidaiakIkusiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BidaiakIkusiButtonActionPerformed

    private void ErabiltzaileakIkusiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErabiltzaileakIkusiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErabiltzaileakIkusiButtonActionPerformed

    private void HistorialaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorialaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kudeaketaPanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kudeaketaPanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kudeaketaPanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kudeaketaPanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kudeaketaPanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BidaiakIkusiButton;
    private javax.swing.JButton ErabiltzaileakIkusiButton;
    private javax.swing.JButton GidariakKudeatuButton;
    private javax.swing.JPanel HeaderPanela;
    private javax.swing.JLabel HeaderTituloa;
    private javax.swing.JButton HistorialaButton;
    private javax.swing.JTable HistorikoaTable;
    private javax.swing.JScrollPane HistorikoajScrollPane;
    private javax.swing.JPanel MenuPanela;
    private javax.swing.JPanel PantallaNagusia;
    private javax.swing.JLabel SakatutakoBotoiarenTituloa;
    // End of variables declaration//GEN-END:variables
}
