version: '3.8'

# Kontenedoreak edukiko dituen zerbitzuak
services:

  # Web zerbitzuarentzeko nginx erabiliko dugu
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php

  # PHP zerbitzuarentzeko PHP-FPM erabiliko dugu
  php:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"

  # PHPMyAdmin zerbitzuarentzeko phpmyadmin erabiliko dugu
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=host.docker.internal
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    ports:
      - "8080:80"
    depends_on:
      - php

  # MySQL zerbitzuarentzeko MySQL erabiliko dugu
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # Ezarri root erabiltzailearentzako pasahitza
      MYSQL_DATABASE: alaiktomugi  # Datu Basearen izena
    ports:
      - "3307:3306"

networks:
  default:
    driver: bridge
